@basesettings = http://localhost:5289

GET {{basesettings}}/games

###
GET {{basesettings}}/games/1

###
POST {{basesettings}}/games
Content-Type: application/json

{
    "name" : "Super Mario Bros. Wonder",
    "genra" : "Platformer",
    "price" : 59.99,
    "releaseDate" : "2023-10-20"
}

###
PUT {{basesettings}}/games/1
Content-Type: application/json

{
"name": "Street Fighter II Turbo",
"genre": "Fighting",
"price": 9.99,
"releaseDate": "1992-07-15"
}